#浮点转整数
int_num=int(11.52)
print(type(int_num),int_num)
#整数转浮点
float_num=float(11)
print(type(float_num),float_num)
#字符串转整数
int_num=int("11")
print(type(int_num),int_num)
#字符串转浮点
float_num=float("11.52")
print(type(float_num),float_num)
#布尔转整数
bool_num=int(True)
print(type(bool_num),bool_num)
#整数转字符串
str_num=str(11)
print(type(str_num),str_num)
#浮点转字符串
str_num=str(11.52)
print(type(str_num),str_num)